name: CI

on:
  push:
    branches:
      - testbringup
      - main
      - master
      - DisableCallIntegration 

jobs:

  build:

    runs-on: ubuntu-latest


    steps:
      - name: automated-build-android-app-with-github-action
        uses: amirisback/automated-build-android-app-with-github-action@2.2.4

